spring:
  config:
    import: optional:configserver:http://localhost:8081
  application:
    name: userAction

  mail:
    host: smtp.gmail.com
    port: 587
    username: latifabenzaied23@gmail.com
    password: bbrc gosv vjqa cean
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

