server:
  port: 8888
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: AUTHENTICATION
          uri: lb:http://USER
          predicates:
            - Path=/api/v1/auth/**

        - id: USER
          uri: lb:http://USER
          predicates:
            - Path=/api/v1/user/**

        - id: PASSWORD
          uri: lb:http://USER
          predicates:
            - Path=/api/v1/password/**

        - id: ROLE
          uri: lb:http://USER
          predicates:
            - Path=/api/v1/role/**

        - id: subscription
          uri: lb:http://SUBSCRIPTION
          predicates:
            - Path=/api/v1/subscriptions/**

        - id: tenderInvitation
          uri: lb:http://TENDERINVITATION
          predicates:
            - Path=/api/v1/tenderInvitations/**


application:
  security:
    jwt:
      secret-key: da4ba9db27f108e4bf7e6b5cc7979d73a01b7b42e1a3e0164e1995e94e5ab2078cc3eb95926591b034ed17c06c80d13bac057fc9f210b31511ffb8625ad23830