server:
  port: 8888
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: offer
          uri: lb://OFFER
          predicates:
            - Path=/api/v1/offer-categories/**

        - id: offer
          uri: lb://OFFER
          predicates:
            - Path=/api/v1/offers/**

        - id: offer
          uri: lb://OFFER
          predicates:
            - Path=/api/v1/offer_forms/**

        - id: offer
          uri: lb://OFFER
          predicates:
            - Path=/api/v1/images/**

        - id: quote-generator
          uri: lb://QUOTE-GENERATOR
          predicates:
            - Path=/api/v1/automobile/**

        - id: quote-generator
          uri: lb://QUOTE-GENERATOR
          predicates:
            - Path=/api/v1/health/**





application:
  security:
    jwt:
      secret-key: 3A3819FB8D35506C579DB26CC2B33952550D02BE99FBF626D8F9C4E8E934F1A3