server:
  port: 8888
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: offer
          uri: lb:http://OFFER
          predicates:
            - Path=/api/v1/offer-categories/**

        - id: offer
          uri: lb:http://OFFER
          predicates:
            - Path=/api/v1/offers/**

        - id: offer
          uri: lb:http://OFFER
          predicates:
            - Path=/api/v1/images/**


        - id: quote-generator
          uri: lb:http://QUOTE-GENERATOR
          predicates:
            - Path=/api/v1/automobile/**

        - id: quote-generator
          uri: lb:http://QUOTE-GENERATOR
          predicates:
            - Path=/api/v1/health/**

        - id: AUTHENTICATION
          uri: lb:http://USER
          predicates:
            - Path=/api/v1/auth/**

        - id: USER
          uri: lb:http://USER
          predicates:
            - Path=/api/v1/user/**

        - id: PASSWORD
          uri: lb:http://USER
          predicates:
            - Path=/api/v1/password/**

        - id: ROLE
          uri: lb:http://USER
          predicates:
            - Path=/api/v1/role/**

        - id: JOB
          uri: lb:http://HR
          predicates:
            - Path=/api/v1/job-posting/**

        - id: CANDIDATE
          uri: lb:http://HR
          predicates:
            - Path=/api/v1/candidate/**

        - id: INTERVIEW
          uri: lb:http://HR
          predicates:
            - Path=/api/v1/interview/**

        - id: RESOURCE
          uri: lb:http://HR
          predicates:
            - Path=/api/v1/resource/**

        - id: complaint
          uri: lb:http://COMPLAINT
          predicates:
            - Path=/api/v1/complaint/**


application:
  security:
    jwt:
      secret-key: da4ba9db27f108e4bf7e6b5cc7979d73a01b7b42e1a3e0164e1995e94e5ab2078cc3eb95926591b034ed17c06c80d13bac057fc9f210b31511ffb8625ad23830