server:
  port: 8888
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: offer
          uri: lb://OFFER
          predicates:
            - Path=/api/v1/offer-categories/**

        - id: offer
          uri: lb://OFFER
          predicates:
            - Path=/api/v1/offers/**

        - id: offer
          uri: lb://OFFER
          predicates:
            - Path=/api/v1/offer_forms/**

        - id: offer
          uri: lb://OFFER
          predicates:
            - Path=/api/v1/images/**

        - id: offer
          uri: lb://OFFER
          predicates:
            - Path=/api/v1/purchased_offers/**

        - id: quote-generator
          uri: lb://QUOTE-GENERATOR
          predicates:
            - Path=/api/v1/automobile/**

        - id: quote-generator
          uri: lb://QUOTE-GENERATOR
          predicates:
            - Path=/api/v1/vin/**

        - id: quote-generator
          uri: lb://QUOTE-GENERATOR
          predicates:
            - Path=/api/v1/geoweather/**

        - id: quote-generator
          uri: lb://QUOTE-GENERATOR
          predicates:
            - Path=/api/v1/health/**

        - id: quote-generator
          uri: lb://QUOTE-GENERATOR
          predicates:
            - Path=/api/v1/who/**

        - id: appointment
          uri: lb://APPOINTMENT
          predicates:
            - Path=/api/v1/appointments/**
        - id: payment
          uri: lb://PAYMENT
          predicates:
            - Path=/api/v1/payment-contracts/**

        - id: payment
          uri: lb://PAYMENT
          predicates:
            - Path=/api/v1/payment-plan/**

        - id: wallet-ins
          uri: lb://WALLET-INS
          predicates:
            - Path=/api/v1/Wallet/**

        - id: blockchain
          uri: lb://BLOCKCHAIN
          predicates:
            - Path=/api/v1/blockchain/**

        - id: AUTHENTICATION
          uri: lb:http://USER
          predicates:
            - Path=/api/v1/auth/**

        - id: USER
          uri: lb:http://USER
          predicates:
            - Path=/api/v1/user/**

        - id: PASSWORD
          uri: lb:http://USER
          predicates:
            - Path=/api/v1/password/**

        - id: ROLE
          uri: lb:http://USER
          predicates:
            - Path=/api/v1/role/**

        - id: JOB
          uri: lb:http://HR
          predicates:
            - Path=/api/v1/job-posting/**

        - id: CANDIDATE
          uri: lb:http://HR
          predicates:
            - Path=/api/v1/candidate/**

        - id: INTERVIEW
          uri: lb:http://HR
          predicates:
            - Path=/api/v1/interview/**

        - id: RESOURCE
          uri: lb:http://HR
          predicates:
            - Path=/api/v1/resource/**

        - id: complaint
          uri: lb:http://COMPLAINT
          predicates:
            - Path=/api/v1/complaint/**

        - id: claim
          uri: lb:http://CLAIM
          predicates:
            - Path=/api/v1/claim/**

        - id: incidentType
          uri: lb:http://CLAIM
          predicates:
            - Path=/api/v1/incident_type/**

        - id: response
          uri: lb:http://CLAIM
          predicates:
            - Path=/api/v1/response/**

application:
  security:
    jwt:
      secret-key: da4ba9db27f108e4bf7e6b5cc7979d73a01b7b42e1a3e0164e1995e94e5ab2078cc3eb95926591b034ed17c06c80d13bac057fc9f210b31511ffb8625ad23830